// functions/src/models/constants.ts
export const AGENT_TYPES = {
    ROADMAP_ORCHESTRATOR: 'roadmap_orchestrator',
    REPOSITORY_SCANNER: 'repository_scanner',
    REPOSITORY_SCANNER_MANAGER: 'repository_scanner_manager',
    USER_COMPILER: 'user_compiler',
    PROGRESS_COORDINATOR: 'progress_coordinator',
    DECISION_ENGINE: 'decision_engine',
    CODE_EXTRACTOR: 'code_extractor',
    EDIT_COORDINATOR: 'edit_coordinator',
    COMMUNICATION_HUB: 'communication_hub',
    MESSAGE_PROCESSOR: 'message_processor'
} as const;

export const MESSAGE_TYPES = {
    // User events
    USER_REGISTERED: 'USER_REGISTERED',
    USER_DEPARTED: 'USER_DEPARTED',
    USER_MESSAGE: 'USER_MESSAGE',
    USER_PROGRESS: 'USER_PROGRESS',
    USER_BLOCKED: 'USER_BLOCKED',

    // Task events
    TASK_ASSIGNMENT: 'TASK_ASSIGNMENT',
    TASK_COMPLETED: 'TASK_COMPLETED',
    TASK_BLOCKED: 'TASK_BLOCKED',
    TASK_REASSIGNED: 'TASK_REASSIGNED',

    // Roadmap events
    ROADMAP_CREATED: 'ROADMAP_CREATED',
    ROADMAP_UPDATED: 'ROADMAP_UPDATED',
    ROADMAP_UPDATE_REQUEST: 'ROADMAP_UPDATE',

    // Scanning events
    SCANNER_ALLOCATION: 'SCANNER_ALLOCATION',
    TARGETED_SCAN: 'TARGETED_SCAN',
    SCAN_RESULT: 'SCAN_RESULT',
    SCAN_INSIGHTS: 'SCAN_INSIGHTS',
    REPOSITORY_ANALYSIS: 'REPOSITORY_ANALYSIS',
    SCAN_SUMMARY: 'SCAN_SUMMARY',

    // Communication events
    USER_COMMUNICATION: 'USER_COMMUNICATION',
    ASSISTANCE_NEEDED: 'ASSISTANCE_NEEDED',
    COLLABORATION_REQUEST: 'COLLABORATION_REQUEST',

    // Coordination events
    COORDINATION_UPDATE: 'COORDINATION_UPDATE',
    PROGRESS_MAP_UPDATE: 'PROGRESS_MAP_UPDATE',
    CONFLICTS_DETECTED: 'CONFLICTS_DETECTED',

    // Decision events
    STRATEGIC_SUMMARY: 'STRATEGIC_SUMMARY',
    STRATEGIC_GUIDANCE_REQUEST: 'STRATEGIC_GUIDANCE_REQUEST',
    DECISION_NOTIFICATION: 'DECISION_NOTIFICATION',

    // Code events
    CODE_EXTRACTION_REQUEST: 'CODE_EXTRACTION_REQUEST',
    CODE_EXTRACTED: 'CODE_EXTRACTED',
    EDIT_RECOMMENDATIONS: 'EDIT_RECOMMENDATIONS',

    // System events
    HEALTH_CHECK: 'HEALTH_CHECK',
    ERROR_OCCURRED: 'ERROR_OCCURRED',
    ALERT_TRIGGERED: 'ALERT_TRIGGERED'
} as const;

export const SCANNER_MODES = {
    MINIMAL: 'minimal',
    TARGETED: 'targeted',
    COMPREHENSIVE: 'comprehensive',
    DEEP_DIVE: 'deep_dive',
    CONTINUOUS: 'continuous'
} as const;

export const TASK_STATUS = {
    NOT_STARTED: 'not_started',
    IN_PROGRESS: 'in_progress',
    BLOCKED: 'blocked',
    COMPLETED: 'completed'
} as const;

export const PRIORITY_LEVELS = {
    CRITICAL: 1,
    HIGH: 2,
    MEDIUM: 3,
    LOW: 4
} as const;

export const TOKEN_LIMITS = {
    GEMINI_25_PRO: 128000,
    GEMINI_15_PRO: 128000,
    GEMINI_25_FLASH: 32000,
    CLAUDE_4: 100000,
    CLAUDE_3: 100000,
    O4_MINI: 128000,
    GPT_5_NANO: 16000,
    GPT_5_MINI: 32000,
    GPT_5: 128000
} as const;

export const ERROR_CODES = {
    AGENT_NOT_FOUND: 'AGENT_NOT_FOUND',
    MESSAGE_ROUTING_FAILED: 'MESSAGE_ROUTING_FAILED',
    TOKEN_LIMIT_EXCEEDED: 'TOKEN_LIMIT_EXCEEDED',
    BUDGET_EXCEEDED: 'BUDGET_EXCEEDED',
    HEALTH_CHECK_FAILED: 'HEALTH_CHECK_FAILED',
    INITIALIZATION_FAILED: 'INITIALIZATION_FAILED',
    VALIDATION_FAILED: 'VALIDATION_FAILED'
} as const;
