import { admin as adminEndpoints } from './api/adminEndpoints';
import { chat } from './api/chatEndpoints';
import { github } from './api/githubEndpoints';
import { simpleUsers } from './api/simpleUsers';
import { socket } from './api/socketEndpoint';
import { test } from './api/testEndpoint';
import { users } from './api/userEndpoints';
import { webhooks } from './api/webhooks';
export { adminEndpoints as admin, chat, github, simpleUsers, socket, test, users, webhooks };
export { AGENT_CONFIG } from './config/agents.config';
